# Predict command
## COMMAND: [ python, predict.py ]
# Train command
TRAIN_COMMAND: [ python, train.py ]
LOO_CV_COMMAND: [python, loo_cross_validation.py]

CLASSES:
  - { label: 0,  name: 'idle',                              }
  - { label: 1,  name: 'lifting',                           }
  - { label: 2,  name: 'lowering',                          }
  - { label: 3,  name: 'carrying',                          }

# --- Information about data
# Path to training dataset 
TRAIN_DATA: /Users/kaanbecker/Documents/VSCode/EASE_pretrained_models/DATA/raw/labeled/ 

# Amount of training data used for validation (between 0 and 1)
VALID_SPLIT: 0.2
# Randomly selected test subjects (Not used during LOSO!)
TEST_SUBJECTS: null
SEED: 28
FOLDS: 0

NUM_WORKERS: 12  # Num of workers for data loading
NUM_GPUS: [0, 1, 2]  # How many GPUs to use
WANDB: True
WANDB_KEY: '6e4c1240ab75e6cd5108325b3f17d887be6ebfa9'
PROJ_NAME: 'MonoSelfPAB_downstream'

DATASET: STFT
DATASET_ARGS:
  x_columns: [[Sig_IMU_Back_Acc_x, Sig_IMU_Back_Acc_y, Sig_IMU_Back_Acc_z,
              Sig_IMU_RU_Acc_x, Sig_IMU_RU_Acc_y, Sig_IMU_RU_Acc_z,
              Sig_IMU_LU_Acc_x, Sig_IMU_LU_Acc_y, Sig_IMU_LU_Acc_z,
              Sig_IMU_RL_Acc_x, Sig_IMU_RL_Acc_y, Sig_IMU_RL_Acc_z,
              Sig_IMU_LL_Acc_x, Sig_IMU_LL_Acc_y, Sig_IMU_LL_Acc_z]]  # back, right upper, left upper, right lower accelerometers
  y_column: ['labels']
  padding_val: [0.0]
  # 50==1sec ==> 3000==60sec==1min
  sequence_length: [120]  # Window size (in samples) fed into the model
  frame_shift: [90]  # How much to shift a window (in samples) null=same as sequence_length
  normalize: [True]  # Whether to normalize the training data
  norm_params_path: [params/norm_params/HUNT4_T/normalization_params_STFT_feats78_seqlen599/]
  n_fft: [50]  # Size of Fourier transform (in samples)
  phase: [False]
  hop_length: [null]  # For STFT computation. If None, n_fft//2
  source_freq: [1000]  # Sampling frequency of dataset
  target_freq: [1000]  # Sampling frequency to use for training
  reorientation: [True]  # Reorient axes to be closer to HUNT4 orientation
  unstack_sensors: [True]  # Whether to unstack sensors along feature dimension (True) or stack along time dimension (False)
  #subsample_perc: [4]

# -- Model 
# Which classifier to use 
ALGORITHM: DownstreamMLP
# Arguments for classifier
# (all given as lists in case to perform a GridSearch)
ALGORITHM_ARGS:
  epochs: [50]
  batch_size: [128]
  loss: [CrossEntropyLoss]
  optimizer: [Adam]
  weight_decay: [0.0]
  output_activation: [softmax]
  metrics: [[F1Score,Accuracy,Precision,Recall]]  # Which metrics to log
  lr: [2e-4]
  lr_scheduler: [ExponentialTFDecay]
  # Architecture params
  upstream_algorithm: [TransformerEncoderNetwork]
  upstream_model_path: [params/MonoSelfPAB_upstream/upstream_model.ckpt]
  rmv_upstream_layers: [4]  # remove the last 4 layers: 3metrics+1pred heads
  weighted_sum_layer: [null]  # None=no weighted sum
  fine_tune_step: [0.75]  # when start fine tune in %
  dropout: [0.1]  # Dropout probability
  n_prediction_head_layers: [2]  # Num layers of MLP at end of model
  dim_prediction_head: [1028]  # Dim of hidden layers of MLP at end od model
  upstream_branches: [5]
  branch_merge_operation: [concat]


STORE_CMATS: True  # Store test cmats on disk
STORE_PATH: "/dss/dsshome1/06/ge38qav/Pretrained_Models/experiments_selfPAB/exp_1" #'/Users/kaanbecker/Documents/VSCode/EASE_pretrained_models/SelfPAB/params/MonoSelfPAB_downstream_experiments/MonoSelfPAB_downstream_EASE'
SKIP_FINISHED_ARGS: False

# Metric which defines the best model
EVAL_METRIC: average_f1score
